### ISSUE TITLE
Where is node_modules folder

### ISSUE THREAD

**Issue by iafi01** [SinghDigamber/rnFirebaseAuth#5]
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.
Error: node_modules directory is missing. Please run `npm install` in your project directory.
Couldn't start project. Please fix the errors and restart the project.
Error: Couldn't start project. Please fix the errors and restart the project.
    at startExpoServerAsync (C:\@expo\xdl@57.9.31\src\Project.ts:2087:11)
    at Object.startAsync (C:\@expo\xdl@57.9.31\src\Project.ts:2405:5)
    at action (C:\Users\User\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:181:3)
    at C:\Users\User\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:354:16
    at Command.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:79:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ android: `expo start --android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by rajasgandhi** [comment]
you have to type `npm install` in the root directory

**Comment by olajesu070** [comment]
![image](https://user-images.githubusercontent.com/66469028/188125826-4bcb4724-8e8b-4391-8a1f-c7e9403783d9.png)

unable to resolve modules
